### PR TITLE
You don't seem to accept any new issues

### PR DESCRIPTION
**Pull request by MichaelSp**
And there is also no way to comment, but to send a PR.

### CODE REVIEW

**Comment by jdickey** [comment]
@MichaelSp The implication seems to be that if you find any issues, you're expected to go off by your lonesome, fix them without talking about it to anyone else, and then submit a PR. Forking won't let you spin up issues/"social coding", because the original repo (here) didn't have them.

@claudiofullscreen Just out of curiosity, why is that?

**Comment by MichaelSp** [comment]
@jdickey After confirmation by @claudiofullscreen I'd consider this repository "unmaintained". 
There was a bug I reported more than one year ago and I just came back to see it's progress. But now I don't even know what this bug was about. All I know is that it was issue #23

Workaround could be to open a blank PR to start a discussion about that particular issue.

**Comment by jdickey** [comment]
@MichaelSp Thanks; that makes sense. Sorry if my earlier comment sounded confrontational; was just surprised. I think this is about the second repo I've ever seen that didn't accept issues; the first was a re-push of a repo that the author said in the README was unmaintained and intentionally abandoned. I'll keep that in mind, as I was considering poking at this on a near-future project.

**Comment by MichaelSp** [comment]
Never mind. I'm also curios. What is the recommended way to report/discuss bugs?
And, more importantly, is it really unmaintained?

**Pull request merged**
