### PR TITLE
Fixes "NoMethodError - private method `include' called" when used with Padrino

### PR DESCRIPTION
**Pull request by oranges13**
When used with Padrino, it produces the error

```
NoMethodError - private method `include' called

This fixes that problem.
```

### CODE REVIEW

**Comment by claudiofullscreen** [comment]
Thanks. Looking at why Travis is failing…

**Comment by oranges13** [comment]
It seemed to be having trouble with a gem :(

**Comment by claudiofullscreen** [comment]
@oranges13 Ok, I fixed that in https://github.com/Fullscreen/bh/pull/152 

Could you rebase against master? Thanks

**Comment by oranges13** [comment]
Huzzah!

**Comment by claudiofullscreen** [comment]
Hello again @oranges13 

I don't fully understand why you get the error above. `include` is called on the Module and it's not a private method. Indeed, the tests are passing even without this PR.

I wonder if you are using a different version of padrino… could you tell me with which version you are experiencing the error above?

By the way, the source code of Bh includes a sample Padrino app… would you mind running it and tell me if you still get the error there? All you have to do is clone bh and then:

```sh
cd examples/padrino
bundle install
padrino start
```

and check whether you can see http://localhost:3000 in your browser.

Let me know! Thanks :ribbon:

**Comment by oranges13** [comment]
Yes, it occurred even with your sample app, unmodified.

Downloaded the app, bundle install, padrino start, and received the error
too.

It's padrino 0.13 and Ruby 1.9.3.

**Comment by claudiofullscreen** [comment]
Thanks! Can you copy/paste here the entire error stack that you receive?
Can you also run `ruby -v` and copy/paste here the exact version of Ruby (with patch number)? 

Thanks again!

**Comment by oranges13** [comment]
Here is the version and stack trace.

I switched to this version of ruby using rvm
```
ruby -v
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
```
and created an empty gemset, so it should be pristine. Checked out the repo directly and ran the padrino example.

Here is the [stacktrace](https://github.com/Fullscreen/bh/files/34535/stacktrace.txt)

Just for giggles and grins, I tried other versions of ruby that one might encounter in the wild:
`ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-linux]` did not work (same error as above)
`ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]` worked!
`ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]` also worked.

And finally, just for complete thoroughness, I used the version of padrino from rubygems as it appears the patch you're checking out in the Gemfile has been committed:
`ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]` did not work (same error)
`ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-linux]` did not work (same error as above)
`ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]` worked.
`ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]` also worked.

**Comment by oranges13** [comment]
Modified the gemfile to pull my branch directly: 

`gem 'bh', git: 'https://github.com/oranges13/bh.git', branch: 'private_method_on_padrino'` 

and all four versions work successfully. So something *somewhere* is definitely going on!

**Pull request closed without merging**
